# =====================================================
# Server 설정
# =====================================================
server:
  port: 8080


# =====================================================
# Spring 설정
# =====================================================
spring:
  config:
    activate:
      on-profile: prod


# =====================================================
# NICE api 계약정보
# =====================================================
nice:
  api:
    ci:
      site-code:
      site-pw:
