# =====================================================
# Server 설정
# =====================================================
server:
  port: 8080


# =====================================================
# Spring 설정
# =====================================================
spring:
  config:
    activate:
      on-profile: local
